### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: prepack.prepack is not a function

### ISSUE THREAD

**Issue by ConsoleTVs** [tunnckoCore/rollup-plugin-prepack#15]
```
(node:18760) UnhandledPromiseRejectionWarning: TypeError: prepack.prepack is not a function
    at Object.transform (CENSORED\node_modules\rollup-plugin-prepack\index.js:24:35)
    at CENSORED\node_modules\rollup\dist\rollup.js:12970:25
(node:18760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tunnckoCore** [comment]
Hi. Thanks for the report. Just released and published 1.0.1 with #14 updates.

Should work now.
